### ISSUE TITLE
connect(client)

### ISSUE THREAD

**Issue by liudongrong** [lahsivjar/react-stomp#108]
why `onConnect()` not `onConnect(client)`

**Comment by lahsivjar** [comment]
Client is internal and the component doesn't support passing custom client

**Comment by liudongrong** [comment]
sorry,  what i want to say is `onConnect` , not `connect`
```jsx
<SockJsClient 
  onConnect={(client) => {
    console.log("connect");
    console.log(client);
   // set state 
  }}
/>
```

```jsx
<SockJsClient 
  onConnect={() => {
    console.log("connect");
  }}
  ref={(client) => {
    this.client = client;
    console.log(client);
  }}
/>
```

**Comment by lahsivjar** [comment]
Sorry, I am still not able to completely grasp the use case. Are you proposing to remove `ref` usage?

**Comment by liudongrong** [comment]
I'd use `stateless function component` and `redux`, `ref` doesn't work very well.
In most cases, many people use client after connected.

**Comment by lahsivjar** [comment]
The main purpose of `ref` is to allow sending message since for sending message you need to call `client.sendMessage` and this method cannot be initiated in `onConnect` callback.

**Comment by lahsivjar** [comment]
please reopen if needed
