### ISSUE TITLE
Not able to add headers 

### ISSUE THREAD

**Issue by Prasad-YS** [lahsivjar/react-stomp#109]
I have added headers pramaters in sockjs but in browser console I can't see any headers, could you please help me in this

**Comment by lahsivjar** [comment]
The headers will be sent along with STOMP's `CONNECT` frame which you can view in the network tab after the handshake and connection upgrade.

For example in [this](https://user-images.githubusercontent.com/1427601/43683755-e251db94-98c4-11e8-8364-ddaa66ddee50.png the value) image the value `login:test` is set via headers

**Comment by lahsivjar** [comment]
From the previous message in the issue#60 it seems you are trying to send the `Authorization` header with the handshake request which is not allowed by the underlying sockjs-client. You can read more about it here:

https://stackoverflow.com/questions/32393519/providing-auth-header-with-sockjs
https://github.com/sockjs/sockjs-client/issues/196
https://github.com/sockjs/sockjs-node#authorisation

**Comment by Prasad-YS** [comment]
So we can not set Authorization in SockJS, that becomes security issue. Then what is the purpose of headers attribute ? What we can set over there ?

**Comment by lahsivjar** [comment]
> So we can not set Authorization in SockJS, that becomes security issue.
You authorise yourself before making handshake request. If browser has a cookie for a particular domain then it will pass it to all `HTTP` requests made to that domain. Please read the links I posted above as this is explained well in those and why SockJS chose to not expose cookies to application

> Then what is the purpose of headers attribute ?
STOMP frames are different and the header's allow you to send them in `STOMP-CONNET` frame. If you don't understand this then I suggest go through the web-socket design and read a bit about STOMP.

> What we can set over there ?
You can set authorization header but these are STOMP headers, not for the handshake request.

**Comment by lahsivjar** [comment]
Closing the issue, reopen if needed

**Comment by baotoushashou** [comment]
I met the same issue!

**Comment by lahsivjar** [comment]
@baotoushashou Are you expecting headers in the handshake request?

As per the above discussion, there is no issue here and the component is working as expected

**Comment by baotoushashou** [comment]
> @baotoushashou Are you expecting headers in the handshake request?
> 
> As per the above discussion, there is no issue here and the component is working as expected

No,I just want to add some information with headers when my app sending some messages to the server running with the stomp and the sockjs.
Thanks ,I have solved it with wrapping headers in stomp client.
