### ISSUE TITLE
Component ref is undefined in componentDidMount: react-native

### ISSUE THREAD

**Issue by Blacktoviche** [lahsivjar/react-stomp#110]
I'm trying to access this.clientRef in componentDidMount  it works in reactjs project but not in react-native
It's undefined when trying to access it in componentDidMount 

`<SockJsClient url={SOCKET_DOMAIN} topics={["/user/queue/blabla"]}
                            onMessage={(msg) => { this.onReceivedMesage(msg) }} headers={customHeaders}
                            ref={(client) => { this.clientRef = client }}
                            onConnect={() => { this.onSocketConnected() }}
                            onDisconnect={() => { console.log('WS Dis-Connected'); }}
                            debug={false} />`
I want SockJsClient ref when componentDidMount to set a global var so I can access clientRef in setInterval function

**Comment by lahsivjar** [comment]
Hi @Blacktoviche ,

I suspect something is preventing render for `SockJsClient` causing refs to not be set.

> https://stackoverflow.com/questions/44074747/componentdidmount-called-before-ref-callback/50019873#50019873

This stackoverflow answer explains which cases can cause undefined ref. Please take a look.

**Comment by Blacktoviche** [comment]
Actually there was if() in the render function and it was the cause of the problem
I solved the problem by removing condition and used navigation instead
Thankx
