### ISSUE TITLE
Any options to add headers like Authorization

### ISSUE THREAD

**Issue by zcmgyu** [lahsivjar/react-stomp#12]
Is it possible to specify an Authorization header on the socket connection?

**Comment by lahsivjar** [comment]
@zcmgyu I am adding the options to pass headers in this commit: https://github.com/lahsivjar/react-stomp/commit/7b2eea9ae75e4a42a992239c0f90e43d28fcfc40

Will be merged soon. Is this what you are hoping for?

**Comment by lahsivjar** [comment]
Closing this issue since the enhancement has been added. If required please reopen
