### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by GabrielBB** [lahsivjar/react-stomp#127]
It looks like this library doesn't work with React ^16.9.0. It's throwing: "WebSocket is closed before the connection is established." Maybe because of the new changes about React hooks and stuff? Here is a picture of the console:

![image](https://user-images.githubusercontent.com/8752823/64302016-6e376180-cf4f-11e9-8665-4213340831e5.png)

**Comment by GabrielBB** [comment]
Well, downgraded to React@16.6.3 and it is still showing. I'm just trying to use this library with the backend in this example:

https://spring.io/guides/gs/messaging-stomp-websocket/

**Comment by digz6666** [comment]
@GabrielBB did you fixed your issue?
