### ISSUE TITLE
Header for info request is not sent

### ISSUE THREAD

**Issue by sorin-sabo** [lahsivjar/react-stomp#136]
While trying to integrate with a secure api which allows calls just for authenticated users, this component tries to make the https://<host>/ws/info request without authorization header which of course results in 401 error. I have tried to add headers and subscribeHeaders but it is still not working. Please let me know if that is possible to add to this component.

**Comment by lahsivjar** [comment]
@sorin-sabo 
`subscribeHeaders` are sent with the `CONNECT` frame by the stomp so this should not be what you are looking for. It should be `headers`. Can you attach some more information like network snapshot for the request ?

**Comment by sorin-sabo** [comment]
Sure.
So first thing first let's assume like in my case you have control over both API and react client.
I subscribe the Client using:
```
  onMessageReceive = (msg, topic) => {
    console.log(msg);
    notif.info(msg.content);
  };
    const authHeaders = {
      Authorization: `Bearer ${idToken}`,
    };
<SockJsClient
        url={'https://localhost:8024/ws/'}
        topics={['/topic/public']}
        headers={authHeaders}
        subscribeHeaders={authHeaders}
        onMessage={this.onMessageReceive}
        ref={client => {
          this.clientRef = client;
        }}
        onConnect={client => {
          this.setState({ clientConnected: true });
        }}
        onDisconnect={() => {
          this.setState({ clientConnected: false });
        }}
        debug={true}
      />
```
While my API endpoint is hosted as you can see on `https://localhost:8024/ws/` and it's a spring boot application completely secured - all api call REQUIRE the idToken:

**Comment by szepgergo** [comment]
Hello @sorin-sabo, have you been able to resolve? I ran into the same problem.

**Comment by StefanoMartella** [comment]
Hello, any solution?

**Comment by lahsivjar** [comment]
@StefanoMartella Where is your bearer token saved? It should be in the cookie and passed to the server

**Comment by cfecherolle** [comment]
Hi, I'm not sure if this library is still maintained (sorry for bothering you if it's not)

I would like to reopen this issue, I'm trying to send headers alongs with the `info` request, and even though I'm setting te header  in the component, I can see in my network panel that the header is not added.
Here is my code:
```
        const connectionHeaders = {Authorization: `Bearer ${token}`};
        component = (
            <SockJsClient
                headers={connectionHeaders}
                subscribeHeaders={connectionHeaders}
                onConnect={onConnectHandler}
                onConnectFailure={onConnectFailureHandler}
                onWebSocketError={onWebSocketError}
                onWebSocketClose={onWebSocketClose}
                url={`${getBaseUrl()}/ws`}
                topics={["/user/queue/notify"]}
            />
        );
```
Currently, we do without the header and include an access token in the URL, and parse it in our back-end.
Is it possible to make this work solely with the Authorization header, and avoid including the JWT in the URL?
