### ISSUE TITLE
connect websocket through zuul api gateway rul raise error, but can get connected few second later

### ISSUE THREAD

**Issue by Junpengalaitp** [lahsivjar/react-stomp#164]
When connecting directly to spring boot WebSocket url, there is no issue and pretty fast. But if connecting through zuul api-gateway URL(it'll try to use ws instead of HTTP first), there is a significant delay in connection and raise errors.

front end error:
![image](https://user-images.githubusercontent.com/40727342/85117185-0d181a80-b251-11ea-813f-198f8d362546.png)
code(the URL is api-gateway url):
![image](https://user-images.githubusercontent.com/40727342/85117280-33d65100-b251-11ea-8e27-ec343fa40ee4.png)

backend error:
![image](https://user-images.githubusercontent.com/40727342/85117404-61bb9580-b251-11ea-909b-46273427c622.png)
WebSocket config:
![image](https://user-images.githubusercontent.com/40727342/85117461-7b5cdd00-b251-11ea-9b4e-86ba90cbc8ab.png)
api-gateway config:
![image](https://user-images.githubusercontent.com/40727342/85117571-a6473100-b251-11ea-8949-f1d387c7e260.png)
![image](https://user-images.githubusercontent.com/40727342/85117599-ae06d580-b251-11ea-88eb-0dea0b3b35d4.png)

**Comment by aminmc** [comment]
I couldn't get spring zuul to work with websockets. I'm pretty sure Spring Zuul is using Zuul 1.x and Zuul 2.x supports reverse proxy but Spring wants people to use Spring Gateway instead. 

It might be worth asking in the Spring forum. 

"Spring Cloud is not going to integrate zuul 2.0 as it is not backwards compatible and they just announced a supported branch last week. We have created Spring Cloud Gateway that supports websockets and see. https://github.com/spring-cloud/spring-cloud-gateway/" -> https://stackoverflow.com/questions/48209075/if-zuul-2-0-in-spring-cloud

https://github.com/Netflix/zuul/wiki/Push-Messaging

https://programming.vip/docs/replacing-zuul-with-spring-cloud-gateway-to-access-websocket.html

**Comment by Junpengalaitp** [comment]
> I couldn't get spring zuul to work with websockets. I'm pretty sure Spring Zuul is using Zuul 1.x and Zuul 2.x supports reverse proxy but Spring wants people to use Spring Gateway instead.
> 
> It might be worth asking in the Spring forum.
> 
> "Spring Cloud is not going to integrate zuul 2.0 as it is not backwards compatible and they just announced a supported branch last week. We have created Spring Cloud Gateway that supports websockets and see. https://github.com/spring-cloud/spring-cloud-gateway/" -> https://stackoverflow.com/questions/48209075/if-zuul-2-0-in-spring-cloud
> 
> https://github.com/Netflix/zuul/wiki/Push-Messaging
> 
> https://programming.vip/docs/replacing-zuul-with-spring-cloud-gateway-to-access-websocket.html

Thanks, I double-checked dependencies, the spring-zuul's version is 2.2.1 but the zuul-core it wrapped has version 1.3.1. It's hard to notice, I am considering to switch to spring cloud gateway.
