### ISSUE TITLE
How to use it over https?

### ISSUE THREAD

**Issue by ramkumar-hosalli** [lahsivjar/react-stomp#165]
<img width="542" alt="Screen Shot 2020-07-09 at 12 33 46 PM" src="https://user-images.githubusercontent.com/61572233/87007919-9a131b80-c1e0-11ea-9a33-9dece735e695.png">
<img width="542" alt="Screen Shot 2020-07-09 at 12 35 32 PM" src="https://user-images.githubusercontent.com/61572233/87008019-bdd66180-c1e0-11ea-8133-3bf79c98b2ff.png">

**Comment by ramkumar-hosalli** [comment]
Incompatibile SockJS! Main site uses: "1.4.0", the iframe: "1.0.0"
websocket.js:6 WebSocket connection to ---------- failed: Error during WebSocket handshake: Unexpected response code: 400
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SockJsClient

**Comment by lahsivjar** [comment]
What is the sock-js version of your server?

**Comment by ramkumar-hosalli** [comment]
Hi, it is  "sockjs-client": "1.4.0" and  "react-stomp": "5.0.0",

**Comment by lahsivjar** [comment]
Looks like the WebSocket connection is not able to be established and it is falling back to iframe-based HTTP streaming. For iframe approach, the sockjs version is downloaded based on the URL that is specified. I suspect the URL for sockJs is pointing to version 1.0.0.

You can set the URL when registering the STOMP endpoint in spring. Something like:

```
    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry.addEndpoint("/websocket").withSockJS()
                .setClientLibraryUrl("<sock_js_client_url>");
    }
```

Check this out for more detail: https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#websocket-fallback-xhr-vs-iframe
