### ISSUE TITLE
The connection is not closed when the component will be unmounted.

### ISSUE THREAD

**Issue by zhayes** [lahsivjar/react-stomp#31]
1,The connection isn't closed when the component will be unmounted.
2, Can't find v2.0.0 on npm.  I pasted your client.jsx in '/src'  dict

**Comment by lahsivjar** [comment]
@zhayes 
1. This is a bug will be fixed via PR: https://github.com/lahsivjar/react-stomp/pull/32 and deployed on npm in `2.1.0`
2. Version `2.0.0` is published on npm. Check here https://www.npmjs.com/package/react-stomp

**Comment by lahsivjar** [comment]
Fix has been merged and npm module has been updated to version `2.1.0` with the fix so closing this issue (CC: @zhayes )
