### ISSUE TITLE
Different callbacks for different topics

### ISSUE THREAD

**Issue by WimVanDerZijden** [lahsivjar/react-stomp#40]
You can subscribe to multiple topics with one component, but they will all have the same callback.

I'm not sure what the syntax should be, but it would be nice to be able to set separate callbacks for each topic.

**Comment by WimVanDerZijden** [comment]
Actually, nevermind, after looking in the source code I see you can actually implement onMessage(msg, topic), which allows you to implement different logic for different topics.

Maybe just update the documentation to show that you can do this?

`onMessage(msg[, topic])`

**Comment by lahsivjar** [comment]
@WimVanDerZijden Thanks for pointing it out. Yes the document should be updated
