### ISSUE TITLE
when handshake is refused，function disconnect  could not stop 

### ISSUE THREAD

**Issue by pearpai** [lahsivjar/react-stomp#44]
When the server stops running, restart If the server refused to shake hands, the browser will send handshake requests to the server, can not use the disconnect method, how to make the component stop shaking hands

**Comment by lahsivjar** [comment]
@pearpai Sorry, I couldn't get the issue. Can you share some more information?

**Comment by pearpai** [comment]
I'm very sorry, because a few days ago is my holiday, no reply in a timely manner.
`
public class HttpHandshakeInterceptor implements HandshakeInterceptor {
    @Override
    public boolean beforeHandshake(ServerHttpRequest request, ServerHttpResponse response, WebSocketHandler wsHandler, Map<String, Object> attributes) throws Exception {
        if (request instanceof ServletServerHttpRequest) {
            ServletServerHttpRequest servletRequest = (ServletServerHttpRequest) request;
            HttpSession session = servletRequest.getServletRequest().getSession();
            if (SecurityUtils.getSubject().getPrincipals() == null){
                return false;
            }
            attributes.put("sessionId", session.getId());
            attributes.put(SHIRO_SUBJECT, SecurityUtils.getSubject());
        }
        return true;
    }

    @Override
    public void afterHandshake(ServerHttpRequest request, ServerHttpResponse response, WebSocketHandler wsHandler, Exception exception) {

    }
}
`

if could not get principal, I should refuse to handshake. if I do that, browser constantly send handshake request, and can't stop.
[browser network](http://pearpai.com/img/handshake.png)

**Comment by lahsivjar** [comment]
@pearpai How about passing `autoReconnect` as `false`?

**Comment by pearpai** [comment]
```
<SockJsClient url='/ws/orangeWebSocket'
                              topics={['/app/subscribe', '/topic/sentMsg', '/user/queue/message']}
                              onMessage={(msg) => {

                                  console.log("serve msg is ", msg);

                                  this.props.responseMessage(msg);
                                  if (msg.response === "subscribe_success") {
                                      if (this.disConnectAct === 'true') {
                                          this.clientRef.disconnect();
                                      }
                                  }
                              }}
                              headers={{}}

                              ref={(client) => {
                                  this.clientRef = client;
                                  this.props.sendAction(client);
                              }}
                              autoReconnect={false}
                />
```
 'autoReconnect={false}'  can not stop shaking hands.
Before the service code，now is the front-end code.

**Comment by lahsivjar** [comment]
@pearpai Sorry about the late response, did you find the solution?

 It seems I didn't understand the problem correctly initially. From the looks of your `browser network` picture it looks like sockjs-client is falling back to xhr_streaming transport and is going in an infinite loop. I wonder what happened to the websocket request which led to the fallback.

**Comment by lahsivjar** [comment]
Reopen if the issue still persists
