### ISSUE TITLE
Will you have support for react native?

### ISSUE THREAD

**Issue by Vitormdias** [lahsivjar/react-stomp#49]

**Comment by lahsivjar** [comment]
Hi @Vitormdias,

Currently there is no plan for this however, there is a PR which claims to fix this:
https://github.com/lahsivjar/react-stomp/pull/41/files

If you can confirm the fix I will expedite the merge for that fix.

Cheers!

**Comment by arivanandan** [comment]
Works.

**Comment by lahsivjar** [comment]
@arivanandan @Vitormdias The fix is merged and published as version **3.3.0**
