### ISSUE TITLE
SockJsClient authentication headers

### ISSUE THREAD

**Issue by AndrewMerke** [lahsivjar/react-stomp#60]
Hello, I have question about authentication header adding while subscribing to server.

I am trying to do it like this:
```
       <SockJsClient url={ wsSourceUrl } topics={[this.state.channelId]} headers={"Authorization: `Bearer ${this.token}`"}
          onMessage={ this.onMessageReceive } ref={ (client) => { this.clientRef = client }}
          onConnect={ () => { this.setState({ clientConnected: true }) } }
          onDisconnect={ () => { this.setState({ clientConnected: false }) } }
          debug={ false }/>
```

But Header isn't getting set. What I am doing wrong?

**Comment by lahsivjar** [comment]
The headers will be sent along with the `CONNECT` frame by stomp client. Currently what you are doing doesn't look syntactically correct.

```
const customHeaders = {
    "Authorization": "Bearer ..."
};
<SockJsClient url={ wsSourceUrl } topics={[this.state.channelId]} headers={ customHeaders }
          onMessage={ this.onMessageReceive } ref={ (client) => { this.clientRef = client }}
          onConnect={ () => { this.setState({ clientConnected: true }) } }
          onDisconnect={ () => { this.setState({ clientConnected: false }) } }
          debug={ false }/>
```

**Comment by AndrewMerke** [comment]
Still nothing happens.  I can not connect to websockets.

**Comment by lahsivjar** [comment]
> When I send my request through POSTMAN it returns me correct values.

How do you send this request? Can you attach some screenshots?

**Comment by AndrewMerke** [comment]
![image](https://user-images.githubusercontent.com/34712585/45675020-f5b97400-bb36-11e8-8c4f-957980a3f7d8.png)

**Comment by lahsivjar** [comment]
The headers is send with the connect frame by STOMP after establishing web socket.

If you can mention what you are trying to do I can help you better

**Comment by lahsivjar** [comment]
http://jmesnil.net/stomp-websocket/doc/#connection

you can check this documentation to find out what `headers` does

**Comment by AndrewMerke** [comment]
@lahsivjar, it was problem in my CORS configuration. Thank you for your patients :)
Headers works well.

**Comment by Prasad-YS** [comment]
Finaly What's the syntax to set headers ? What is subscribeHeaders ? Do we need to use this ??

**Comment by lahsivjar** [comment]
@Prasad-YS 

> Finaly What's the syntax to set headers ? 
All headers are JavaScript objects or key-value pairs. Just pass what you require as props to the component

> What is subscribeHeaders ?
`subscribeHeaders` are passed to the server when you subscribe to a new topic

> Do we need to use this ??
It is not required or must, you need to send it only when the server needs it

**Comment by Prasad-YS** [comment]
> @Prasad-YS
> 
> > Finaly What's the syntax to set headers ?
> 
> All headers are JavaScript objects or key-value pairs. Just pass what you require as props to the component
> 
> > What is subscribeHeaders ?
> 
> `subscribeHeaders` are passed to the server when you subscribe to a new topic
> 
> > Do we need to use this ??
> 
> It is not required or must, you need to send it only when the server needs it

const customHeaders = {
      Authorization: "Bearer token"
    };

<SockJsClient url={websockurl} 
          headers={customHeaders} 
          topics={['/' + this.state.radioFilter + '/' + this.state.selectedPeriod]}
          
            onMessage={(msg) => { 
              this._loadData(msg);
            }}
            ref={ (client) => { 
              this.clientRef = client 
            }} debug={true}>
          </SockJsClient>

Not sure what's wrong here, I'm unable to connect to web sock,

before adding the headers it was working fine, now it's not able to connect, The headers not not getting append , could you please help me here 

![Hedders](https://user-images.githubusercontent.com/10754528/55851960-9ecdc780-5b78-11e9-9a72-e634c9c4e866.PNG)
![hedders2](https://user-images.githubusercontent.com/10754528/55851966-a68d6c00-5b78-11e9-880c-6990c184f36d.PNG)

**Comment by lahsivjar** [comment]
@Prasad-YS 
Please create a new issue at https://github.com/lahsivjar/react-stomp/issues/new and we can discuss it there

**Comment by FubuBy** [comment]
@Prasad-YS Did you resolve your problem?

**Comment by Prasad-YS** [comment]
Yes, My problem got resolved

**Comment by FubuBy** [comment]
@Prasad-YS Did you manage to pass the token throw the header of SockJsClient?

**Comment by jitugeo** [comment]
I', not able to pass the token in the header using SockjsClient. can someone help me ?

**Comment by jaure96** [comment]
I have this peace of code. Can´t set headers....
@Prasad-YS and  @lahsivjar can you help?? 

let customHeaders = {}
    const token = login.utils.getAccessToken(store.getState())
    if (token !== null) {
        customHeaders['Authorization'] = 'Bearer ' + token
        customHeaders['Access-Control-Allow-Origin'] = '*'
    }
    return (
        <SockJsClient
            headers={customHeaders}
            url='http://localhost:44442/websocket-chat/'
            topics={['/topic/user']}
            onConnect={() => {
                console.log("connected");
            }}
            onDisconnect={() => {
                console.log("Disconnected");
            }}
            onMessage={(msg) => {
                console.log(msg);
            }}
            ref={(client) => {
                this.clientRef = client
            }} />
    )

**Comment by crisilva95** [comment]
@Prasad-YS How did your solve it?
 I have the exact same problem, headers don't even show up on the request.

**Comment by bkeren** [comment]
instead of giving at header; I gave the token as request parameter named **authorization** at endpoint of we websocket connection and it worked
