### ISSUE TITLE
How to resubscribe to topic

### ISSUE THREAD

**Issue by AndrewMerke** [lahsivjar/react-stomp#78]
Hello, how could I re-subscribe to different topic? 
I am using your lib like this. But after Component re-render .${this.channelId} is taken correctly, but websockets connection stays at same topic. How could I workaround this problem?
```
           <SockJsClient
             url={wsSourceUrl}
             topics={[`/topic/private.chat.${this.channelId}`]}
             headers={customHeaders}
             onMessage={this.onMessageReceive}
             ref={client => {
               this.clientRef = client;
             }}
             onConnect={() => {
               this.setState({ clientConnected: true });
             }}
             onDisconnect={() => {
               this.setState({ clientConnected: false });
             }}
             debug={false}
           />
         </div>
```

**Comment by lahsivjar** [comment]
@AndrewMerke Save the topics as the state of the parent component and pass it to `SockJsClient` as this:

```
<SockJsClient 
    ...
    topics={ this.state.topics }
    ... />
```

Then update the state whenever required. For example:

```
this.setState(prevState => ({
    topics: [...prevState.topics, "/newtopic"]
}));
```

**Comment by AndrewMerke** [comment]
But how to trigger that from another component? In my case I store this.channelId in sessionStorage. And I would like after that change subscrite to another topic.

**Comment by lahsivjar** [comment]
> they are sent correctly I can console.log them or check in Database, aslo if I reload page I can see them

Where are you not able to see them? Do you mean `this.state.messages` doesn't have the received message? (react-stomp doesn't provide any UI to show messages in)

**Comment by AndrewMerke** [comment]
Thank you for your advice and hints :) And lead me on the right way.
