### ISSUE TITLE
Manage subscription to topics by updating properties passed to the component

### ISSUE THREAD

**Issue by lahsivjar** [lahsivjar/react-stomp#8]

**Comment by KIC** [comment]
How would you implement this conceptually. Since you can only subscribe after the connect callback this could be a tricky one.

**Comment by lahsivjar** [comment]
@KIC I was thinking of deciding in `componentWillReceiveProps` about subscribing to new topics or unsubscribing old ones based on the difference between old props and the new one and the current state of the websocket connection.

**Comment by KIC** [comment]
true, I think this could be easily done with lodash/underscore like:

```
  componentWillReceiveProps(nextProps) {
    if (this.state.connected) {
      // new topics
      _.pullAll(nextProps.topics.slice(), this.props.topics)
       .forEach(topic => this.subscribe(topic))
      
       // obsolete topics
      _.pullAll(this.props.topics.slice(), nextProps.topics)
       .forEach(topic => this.unsubscribe(topic))
    } else {
      this.props.topics = _.intersection(this.props.topics, nextProps.topics)
    }
  }

```
What do you think?

**Comment by lahsivjar** [comment]
@KIC Using loadash looks good to me. PR's are welcomed. If you can create a PR we can discuss it there
