### ISSUE TITLE
can't connect with android

### ISSUE THREAD

**Issue by tal987** [lahsivjar/react-stomp#81]
hi im having an issue with android physical device. on iOS everything works great but on android I don't see any connection what might be the problem?

I was thinking maybe different local host

**Comment by lahsivjar** [comment]
@tal987 Can you post some network logs or server side logs for more information?

**Comment by tal987** [comment]
@lahsivjar thanks for you comment.
just to be more clear, I was checking on physical device (android and iOS) on both of them its not working... I don't see any error, but I know that theres no connection to the server(in spring) but when im using emulator theres no problem... what might be the problem? maybe when I connected with physical device theres a different url? so far im using this url: http://localhost:9000/gs-guide-websocket and its working only on emulator...

**Comment by lahsivjar** [comment]
It is not possible to speculate what the problem can be without logs. I suggest you enable debug in the component and try to check logs. If you can post some logs I can help.

To enable debug:

```
        <SockJsClient ... debug={ true } />
```

**Comment by tal987** [comment]
@lahsivjar I think I know what's the issue, when you use simulator you can connect to your own server with localhost but when you use physical device you cant connect to your localhost but you can connect to remote server or to the ip of your own computer...

**Comment by lahsivjar** [comment]
Glad you found the issue.
