### ISSUE TITLE
message:Connection to broker closed.

### ISSUE THREAD

**Issue by giscafer** [lahsivjar/react-stomp#84]
![whoops](https://user-images.githubusercontent.com/8676711/48125335-68cea380-e2b9-11e8-85fa-7ba2092329bc.png)

Error :Connection to broker closed.

```jsx
  onMessageReceive = (msg) => {
    console.log(`onMessage:${msg}`)
  }
  sendMessage = (billNo) => {
    let qryParams = {
      "yztIdCode": "111",
      "inwarehouseNo": billNo//入库单号
    };
    this.clientRef.sendMessage("/action/collectConfirmPda", JSON.stringify(qryParams));
  }

  onConnect() {
    this.sendMessage(this.props.navigation.state.params.billNo);
    this.setState({ clientConnected: true });
  }
  onDisconnect() {
    this.setState({ clientConnected: false });
  }
  render() {
    const billNo = this.props.navigation.state.params.billNo;
    const wsUrl = 'http://192.168.16.144:18004/websocket/wms-stockInfo-endpoint';
    const customHeaders = {
      "Authorization": `Bearer ${getTokenCache()}`
    };
    return (
      <View style={{ flex: 1 }}>
        <ScanCodeDetails
          dataList={this.plainList}
          title={'入库单'}
          currentId={this.props.navigation.state.params.billNo}
          changeVisible={this.props.changeVisible}
          submit={this.props.submit}
          navigation={this.props.navigation}
          getDataList={this.props.getDataList}
        />
        <SockJsClient url={wsUrl}
          topics={[`/topic/collectConfirmPda${billNo}`]}
          headers={customHeaders}
          onConnect={() => { this.onConnect() }}
          onDisconnect={() => { this.onDisconnect() }}
          onMessage={this.onMessageReceive} ref={(client) => { this.clientRef = client }} debug={true} />
      </View>
    );
  }
```

**Comment by lahsivjar** [comment]
@giscafer The log suggest that the ERROR frame is sent from server side. Please check server logs

**Comment by giscafer** [comment]
@lahsivjar but my ng web application doesn't  cause this issue by using the [ng2-stompjs](https://github.com/stomp-js/ng2-stompjs) under the same websocket server。

when i use react-stomp in react native app cause this issue, i have no idea deal with this，server logs is seems normal

**Comment by lahsivjar** [comment]
I see. Can you share the network logs?

1. open chrome dev tools -> network tab
2. reload your page
3. under network tab locate the ws tab and find your ws connection
4. share the frames view

**Comment by lahsivjar** [comment]
Can you confirm the same behaviour in some other browsers other than chrome?

**Comment by giscafer** [comment]
@lahsivjar i want to know how to set the network ws tab can see the logs in react native。i only can see http request in  xhr tab logs

**Comment by giscafer** [comment]
![image](https://user-images.githubusercontent.com/8676711/48180589-2bbcec80-e35f-11e8-9b1a-e31b9c9e5501.png)

when the view rerender , the component SockJsClient will rerender lead to  reconnect websock?

**Comment by piyushkathayat** [comment]
did someone solve this issue?
