### ISSUE TITLE
subscribe headers not properly typped

### ISSUE THREAD

**Issue by daniel-exceed** [lahsivjar/react-stomp#95]
the prop type of subscribe headers is object instead of array, this prints an annoying warning every time in the browser

**Comment by lahsivjar** [comment]
@daniel-exceed Seems to be some misunderstanding, the `subscribeHeaders` is an object not an array, you can check the document of the underlying client (`stomp-websocket`) for more details: http://jmesnil.net/stomp-websocket/doc/

Reopen the ticket if there again if required.
