### ISSUE TITLE
react-stomp for redux

### ISSUE THREAD

**Issue by Tsyklop** [lahsivjar/react-stomp#97]
I make ReactJs app with redux. I want use your library, but i need redux.
Are you can make version for redux?

**Comment by lahsivjar** [comment]
Hi @Tsyklop ,

The only state `react-stomp` manages are connection state which can be treated as internal states. As such there should be no problem when using with redux.

Some more info here: https://redux.js.org/faq/organizing-state#do-i-have-to-put-all-my-state-into-redux-should-i-ever-use-react-s-setstate

Let me know if there is something more to it and reopen the issue

**Comment by Tsyklop** [comment]
@lahsivjar Okay. But how i can send message? or subscribe? i need inject react-stomp instance every component? I need single websocket instance and using it in deep in my components
