### ISSUE TITLE
subscribe headers treated like array and sliced

### ISSUE THREAD

**Issue by daniel-exceed** [lahsivjar/react-stomp#99]
subscribe headers treated like array instead of object

**Comment by daniel-exceed** [comment]
fix:
https://github.com/lahsivjar/react-stomp/pull/96

**Comment by lahsivjar** [comment]
Merged

**Comment by EmilianStankov** [comment]
Hi @lahsivjar, can this fix be added to a release version? 😓

**Comment by lahsivjar** [comment]
@EmilianStankov Sorry, my bad. Released it under version 4.1.1

https://www.npmjs.com/package/react-stomp/v/4.1.1

**Comment by EmilianStankov** [comment]
Thank you!
